apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    # Note: uses GKE workload identity for service account
    solvers:
    - dns01:
        clouddns:
          project: {{ .Values.gcpProject }}
