platform: linux

image_resource:
  type: registry-image
  source: { repository: google/cloud-sdk }

inputs:
  - name: greenpeace
  - name: production-terraform

params:
  GCP_CREDENTIALS_JSON:
  GREENPEACE_PRIVATE_KEY:
  TERRAFORM_VERSION: 0.12.24

run:
  path: greenpeace/tasks/scripts/initialize-vault.sh