platform: linux

image_resource:
  type: registry-image
  source: { repository: google/cloud-sdk }

inputs:
  - name: greenpeace
  - name: terraform

params:
  GCP_CREDENTIALS_JSON:
  GREENPEACE_PRIVATE_KEY:
  CLUSTER_NAME:
  TERRAFORM_VERSION: 0.12.26

run:
  path: greenpeace/tasks/scripts/initialize-vault.sh
  user: root
