platform: linux

image_resource:
  type: registry-image
  source: { repository: google/cloud-sdk }

inputs:
  - name: greenpeace
  - name: production-terraform

outputs:
  - name: vault-token

params:
  GCP_CREDENTIALS_JSON:

run:
  path: greenpeace/tasks/scripts/initialize-vault.sh