platform: linux
config:
  image_resource:
    type: registry-image
    source: { repository: google/cloud-sdk }

inputs:
  - name: greenpeace
  - name: production-terraform

run:
  path: greenpeace/tasks/scripts/initialize-vault.sh