platform: linux

image_resource:
  type: registry-image
  source: {repository: alpine/git}

inputs:
- name: repo

outputs:
- name: repo-bumped
  path: repo

params:
  FILE:
  # A JSON object - for each key, replace the value in the file with the value
  # in the object.
  PATCH:
  COMMIT:

run:
  path: sh
  args:
  - -c
  - |
    set -e

    apk add jq

    cd repo

    echo "$PATCH" | jq -r '. | to_entries | .[] | @base64' | while read line; do
      key=$(echo "$line" | base64 --decode | jq -r '.key')
      value=$(echo "$line" | base64 --decode | jq -r '.value')

      sed -i "s/^$key:.*/$key: $value/" "$FILE"
    done

    git add -A

    git config --global user.email "ci@localhost"
    git config --global user.name "CI Bot"

    git commit -m "$COMMIT" --allow-empty
