resource_types:
- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: '0.12.29'

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: greenpeace
  type: git
  source:
    uri: git@github.com:concourse/greenpeace.git
    private_key: ((greenpeace_private_key))

- name: terraform
  type: terraform
  source:
    env_name: ((cluster))
    backend_type: gcs
    backend_config:
      bucket: concourse-greenpeace
      prefix: terraform
      credentials: ((gcp_credentials_json))
    vars:
      credentials: ((gcp_credentials_json))
      datadog_api_key: ((datadog_api_key))
      datadog_app_key: ((datadog_app_key))

- name: secrets
  type: gcs
  source:
    bucket: concourse-greenpeace
    json_key: ((gcp_credentials_json))
    versioned_file: vault/production/data.tar

- name: vault-backend-migrator
  type: gcs
  source:
    bucket: concourse-greenpeace
    json_key: ((gcp_credentials_json))
    versioned_file: vault/bin/vault-backend-migrator

jobs:
- name: terraform
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: greenpeace
    - get: secrets
      params:
        unpack: true
    - get: vault-backend-migrator
  - put: terraform
    params:
      terraform_source: greenpeace/terraform/((cluster))
    get_params:
      output_statefile: true
  - task: initialize-vault
    file: greenpeace/tasks/initialize-vault.yml
    params:
      GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
      GREENPEACE_PRIVATE_KEY: ((greenpeace_private_key))
      CLUSTER_NAME: ((cluster))
