resource_types:
- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: '0.12.24'

resources:
- name: greenpeace
  type: git
  source:
    uri: git@github.com:concourse/greenpeace.git
    private_key: ((greenpeace_private_key))

- name: terraform
  type: terraform
  source:
    env_name: ((cluster))
    backend_type: gcs
    backend_config:
      bucket: concourse-greenpeace
      prefix: terraform
      credentials: ((gcp_credentials_json))
    vars:
      credentials: ((gcp_credentials_json))

jobs:
- name: terraform
  max_in_flight: 1
  plan:
  - get: greenpeace
  - put: terraform
    params:
      terraform_source: greenpeace/terraform/((cluster))
    get_params:
      output_statefile: true
  - task: initialize-vault
    file: greenpeace/tasks/initialize-vault.yml
    params:
      GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
      GREENPEACE_PRIVATE_KEY: ((greenpeace_private_key))
      CLUSTER_NAME: ((cluster))
