resource_types:
- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: '0.13.5'

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: greenpeace
  type: git
  source:
    uri: git@github.com:concourse/greenpeace.git
    private_key: ((greenpeace_private_key))

- name: terraform
  type: terraform
  source:
    env_name: ((cluster))
    backend_type: gcs
    backend_config:
      bucket: concourse-greenpeace
      prefix: terraform
      credentials: ((gcp_credentials_json))
    vars:
      credentials: ((gcp_credentials_json))

- name: secrets
  type: gcs
  source:
    bucket: concourse-greenpeace
    json_key: ((gcp_credentials_json))
    versioned_file: vault/production/data.tar

jobs:
- name: terraform
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: greenpeace
    - get: secrets
      params:
        unpack: true
    - get: vault-backend-migrator
  - put: terraform
    params:
      terraform_source: greenpeace/terraform/((cluster))
    get_params:
      output_statefile: true
  - task: compile-vault-backend-migrator
    file: greenpeace/tasks/compile
    params:
      PATH: ./vendor/vault-backend-migrator
    input_mapping:
      repo: greenpeace
    output_mapping:
      compiled: vault-backend-migrator
  - task: initialize-vault
    file: greenpeace/tasks/initialize-vault.yml
    params:
      GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
      GREENPEACE_PRIVATE_KEY: ((greenpeace_private_key))
      CLUSTER_NAME: ((cluster))
      TERRAFORM_VERSION: '0.13.5'
- name: terraform-destroy
  max_in_flight: 1
  plan:
  - get: greenpeace
  - put: terraform
    params:
      terraform_source: greenpeace/terraform/((cluster))
      action: destroy
    get_params:
      action: destroy
