resource_types:
- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: '0.13.5'

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: greenpeace
  type: git
  source:
    uri: git@github.com:concourse/greenpeace.git
    private_key: ((greenpeace_private_key))

- name: daily
  type: time
  source:
    start: 2:00 AM
    stop: 3:00 AM

- name: terraform
  type: terraform
  source:
    env_name: ((cluster))
    backend_type: gcs
    backend_config:
      bucket: concourse-greenpeace
      prefix: terraform
      credentials: ((greenpeace_gcp_credentials_json))
    vars:
      credentials: ((greenpeace_gcp_credentials_json))

- name: secrets
  type: gcs
  source:
    bucket: concourse-greenpeace
    json_key: ((greenpeace_gcp_credentials_json))
    versioned_file: vault/((cluster))/data.tar

- name: production-secrets
  type: gcs
  source:
    bucket: concourse-greenpeace
    json_key: ((greenpeace_gcp_credentials_json))
    versioned_file: vault/production/data.tar

- name: root-token-enc
  type: gcs
  source:
    bucket: concourse-greenpeace
    json_key: ((greenpeace_gcp_credentials_json))
    versioned_file: vault/((cluster))/root-token.enc

jobs:
- name: sync-secrets-with-production
  plan:
  - get: production-secrets
  - put: secrets
    params:
      file: production-secrets/data.tar

- name: terraform
  max_in_flight: 1
  plan:
  - get: greenpeace
  - put: terraform
    params:
      terraform_source: greenpeace/terraform/((cluster))

- name: initialize-vault
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: greenpeace
    - get: secrets
      trigger: true
      params:
        unpack: true
    - get: terraform
      trigger: true
      passed: [terraform]
      params:
        output_statefile: true
  - task: compile-vault-backend-migrator
    file: greenpeace/tasks/compile.yml
    params:
      CONTEXT: vendor/vault-backend-migrator
    input_mapping:
      repo: greenpeace
    output_mapping:
      compiled: vault-backend-migrator
  - task: initialize-vault
    file: greenpeace/tasks/initialize-vault.yml
    params:
      GCP_CREDENTIALS_JSON: ((greenpeace_gcp_credentials_json))
      GREENPEACE_PRIVATE_KEY: ((greenpeace_private_key))
      CLUSTER_NAME: ((cluster))
      TERRAFORM_VERSION: '0.13.5'

- name: backup-secrets
  max_in_flight: 1
  plan:
  - in_parallel:
    - get: greenpeace
    - get: terraform
    - get: root-token-enc
    - get: daily
      trigger: true
  - task: compile-vault-backend-migrator
    file: greenpeace/tasks/compile.yml
    params:
      CONTEXT: vendor/vault-backend-migrator
    input_mapping:
      repo: greenpeace
    output_mapping:
      compiled: vault-backend-migrator
  - task: export-secrets
    file: greenpeace/tasks/export-secrets.yml
  - put: secrets
    params:
      file: secrets/data.tar

- name: terraform-destroy
  max_in_flight: 1
  plan:
  - get: greenpeace
  - put: terraform
    params:
      terraform_source: greenpeace/terraform/((cluster))
      action: destroy
    get_params:
      action: destroy
