apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.name }}
spec:
  secretName: {{ .Values.secretName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
    - concourse
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ .Values.dnsName }}
  issuerRef:
    name: {{ .Values.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
